name: Examples

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  ARTILLERY_BINARY_PATH: ${{ github.workspace }}/packages/artillery/bin/run
  CLI_TAGS: repo:${{ github.repository }},actor:${{ github.actor }},type:smoke,ci:true
  CLI_NOTE: Running&nbsp;from&nbsp;the&nbsp;Official&nbsp;Artillery&nbsp;Github&nbsp;Action!&nbsp;ðŸ˜€

jobs:
  browser-load-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CWD: ./examples/browser-load-testing-playwright
    defaults:
      run:
        working-directory: ${{ env.CWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run example
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: |
          $ARTILLERY_BINARY_PATH run browser-load-test.ts --record --tags ${{ env.CLI_TAGS }},group:browser-load-test --note "${{ env.CLI_NOTE }}"
        working-directory: ${{ env.CWD }}
        env:
          ARTILLERY_BINARY_PATH: ${{ env.ARTILLERY_BINARY_PATH }}
          ARTILLERY_CLOUD_ENDPOINT: ${{ secrets.ARTILLERY_CLOUD_ENDPOINT_TEST }}
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY_TEST }}

  http-metrics-by-endpoint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CWD: ./examples/http-metrics-by-endpoint
    defaults:
      run:
        working-directory: ${{ env.CWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        uses: artilleryio/action-cli@v1
        with:
          command: run ./endpoint-metrics.yml --record --tags ${{ env.CLI_TAGS }},group:http-metrics-by-endpoint --note ${{ env.CLI_NOTE }}
          working-directory: ${{ env.CWD }}
        env:
          ARTILLERY_BINARY_PATH: ${{ env.ARTILLERY_BINARY_PATH }}
          ARTILLERY_CLOUD_ENDPOINT: ${{ secrets.ARTILLERY_CLOUD_ENDPOINT_TEST }}
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY_TEST }}

  multiple-scenarios-spec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CWD: ./examples/multiple-scenario-specs
    defaults:
      run:
        working-directory: ${{ env.CWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Run armadillo scenario
        uses: artilleryio/action-cli@v1
        with:
          command: run --config ./common-config.yml ./scenarios/armadillo.yml --record --tags ${{ env.CLI_TAGS }},group:multiple-scenario-specs --note ${{ env.CLI_NOTE }}
          working-directory: ${{ env.CWD }}
        env:
          ARTILLERY_BINARY_PATH: ${{ env.ARTILLERY_BINARY_PATH }}
          ARTILLERY_CLOUD_ENDPOINT: ${{ secrets.ARTILLERY_CLOUD_ENDPOINT_TEST }}
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY_TEST }}

      - name: Run dino scenario
        uses: artilleryio/action-cli@v1
        with:
          command: run --config ./common-config.yml ./scenarios/dino.yml --record --tags ${{ env.CLI_TAGS }},group:multiple-scenario-specs --note ${{ env.CLI_NOTE }}
          working-directory: ${{ env.CWD }}
        env:
          ARTILLERY_BINARY_PATH: ${{ env.ARTILLERY_BINARY_PATH }}
          ARTILLERY_CLOUD_ENDPOINT: ${{ secrets.ARTILLERY_CLOUD_ENDPOINT_TEST }}
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY_TEST }}

  using-data-from-csv:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CWD: ./examples/using-data-from-csv
    defaults:
      run:
        working-directory: ${{ env.CWD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test
        uses: artilleryio/action-cli@v1
        with:
          command: run ./website-test.yml --record --tags ${{ env.CLI_TAGS }},group:using-data-from-csv --note ${{ env.CLI_NOTE }}
          working-directory: ${{ env.CWD }}
        env:
          ARTILLERY_BINARY_PATH: ${{ env.ARTILLERY_BINARY_PATH }}
          ARTILLERY_CLOUD_ENDPOINT: ${{ secrets.ARTILLERY_CLOUD_ENDPOINT_TEST }}
          ARTILLERY_CLOUD_API_KEY: ${{ secrets.ARTILLERY_CLOUD_API_KEY_TEST }}
