name: Publish Skytrace CLI to npm
on:
  push:
    branches:
      - main
    paths:
      - packages/skytrace/package.json
jobs:
  build:
    if: "contains(github.event.head_commit.message, 'ci: release v')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@artilleryio'
      - run: PACKAGE_FOLDER_NAME=skytrace node .github/workflows/scripts/rename-packages-to-latest.js
      - run: npm run build -w skytrace
      - run: npm -w skytrace publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
